import type { Metadata } from "next";
import "./globals.css";
import OCConnectWrapper from "./components/OCConnectWrapper";

export const metadata: Metadata = {
  title: "Tank Duel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const opts = {
    redirectUri: 'http://localhost:3000/main', 
    referralCode: 'PARTNER6',
  };

  return (
    <html lang="en">
      <body>
        <OCConnectWrapper opts={opts} sandboxMode={true}>
          {children}
        </OCConnectWrapper>
      </body>
    </html>
  );
}
